services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: longpassphrase
      POSTGRES_DB: billingdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
